Repository FabricMC/fabric-loader, pull requests merged in 2020-10, with the labels that each got.

#306 Yeet Gson from loader
  build.gradle
  gradle.properties
  src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java
  src/main/java/net/fabricmc/loader/discovery/ModResolver.java
  src/main/java/net/fabricmc/loader/game/GameProviderHelper.java
  src/main/java/net/fabricmc/loader/game/MinecraftGameProvider.java
  src/main/java/net/fabricmc/loader/launch/knot/KnotClassLoader.java
  src/main/java/net/fabricmc/loader/lib/gson/JsonReader.java
  src/main/java/net/fabricmc/loader/lib/gson/JsonScope.java
  src/main/java/net/fabricmc/loader/lib/gson/JsonToken.java
  src/main/java/net/fabricmc/loader/lib/gson/MalformedJsonException.java
  src/main/java/net/fabricmc/loader/metadata/AbstractModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/ContactInfoBackedPerson.java
  src/main/java/net/fabricmc/loader/metadata/CustomValueImpl.java
  src/main/java/net/fabricmc/loader/metadata/LoaderModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/ModDependencyImpl.java
  src/main/java/net/fabricmc/loader/metadata/ModMetadataParser.java
  src/main/java/net/fabricmc/loader/metadata/ModMetadataV0.java
  src/main/java/net/fabricmc/loader/metadata/ModMetadataV1.java
  src/main/java/net/fabricmc/loader/metadata/ParseMetadataException.java
  src/main/java/net/fabricmc/loader/metadata/ParseWarning.java
  src/main/java/net/fabricmc/loader/metadata/SimplePerson.java
  src/main/java/net/fabricmc/loader/metadata/V0ModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/V0ModMetadataParser.java
  src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/V1ModMetadataParser.java
  src/main/java/net/fabricmc/loader/minecraft/McVersionLookup.java
  src/main/java/net/fabricmc/loader/util/version/VersionDeserializer.java
  src/test/java/net/fabricmc/test/V1ModJsonParsingTests.java
  src/test/java/net/fabricmc/test/mixin/MixinGuiMain.java
  src/test/resources/fabricmc.test.mixins.client.json
  src/test/resources/testing/parsing/README.md
  src/test/resources/testing/parsing/v1/error/duplicate_mismatched_schema_versions.json
  src/test/resources/testing/parsing/v1/error/missing_version.json
  src/test/resources/testing/parsing/v1/spec/custom_values.json
  src/test/resources/testing/parsing/v1/spec/example_1.json
  src/test/resources/testing/parsing/v1/spec/long.json
  src/test/resources/testing/parsing/v1/spec/required.json
  src/test/resources/testing/parsing/v1/spec/required_reversed.json
Labels: enhancement, merge me please

#324 Fix error from json migration
  src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java
Labels: bug

#320 Buildscript update/cleanup
  .github/workflows/build.yml
  .gitignore
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/test/java/net/fabricmc/test/VersionParsingTests.java
  src/test/java/net/fabricmc/test/mixin/MixinGuiMain.java
Labels: enhancement

#277 Add friendlier dependency resolution error descriptions
  src/main/java/net/fabricmc/loader/api/VersionPredicate.java
  src/main/java/net/fabricmc/loader/api/metadata/ModDependency.java
  src/main/java/net/fabricmc/loader/discovery/ModResolver.java
  src/main/java/net/fabricmc/loader/gui/FabricMainWindow.java
  src/main/java/net/fabricmc/loader/gui/FabricStatusTree.java
  src/main/java/net/fabricmc/loader/metadata/ModDependencyImpl.java
Labels: enhancement

#204 Clean up mod resolution error messages
  src/main/java/net/fabricmc/loader/discovery/ModResolver.java
Labels: enhancement
