Repository FabricMC/fabric-loader, pull requests merged in 2021-01, with the labels that each got.

#358 Fix manifests when doing runtime mod remapping
  src/main/java/net/fabricmc/loader/discovery/RuntimeModRemapper.java
Labels: merge me please

#350 Add the current Java version as a built-in dependency
  src/main/java/net/fabricmc/loader/discovery/ModResolver.java
Labels: merge me please

#340 Add a more specific error message when finding positive (but unsupported) schema versions.
  src/main/java/net/fabricmc/loader/metadata/ModMetadataParser.java
Labels: enhancement, merge me please

#334 Add aliases to Fabric Loader
  src/main/java/net/fabricmc/loader/FabricLoader.java
  src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java
  src/main/java/net/fabricmc/loader/discovery/BuiltinMetadataWrapper.java
  src/main/java/net/fabricmc/loader/discovery/ModCandidateSet.java
  src/main/java/net/fabricmc/loader/discovery/ModResolver.java
  src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/V0ModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/V1ModMetadataParser.java
Labels: enhancement, merge me please

#313 Make EntrypointContainer lazy
  src/main/java/net/fabricmc/loader/EntrypointStorage.java
  src/main/java/net/fabricmc/loader/api/entrypoint/EntrypointContainer.java
  src/main/java/net/fabricmc/loader/entrypoint/EntrypointContainerImpl.java
Labels: enhancement, merge me please

#360 Dependency Overrides
  src/main/java/net/fabricmc/loader/FabricLoader.java
  src/main/java/net/fabricmc/loader/metadata/DependencyOverrides.java
  src/main/java/net/fabricmc/loader/metadata/V0ModMetadata.java
  src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java
Labels: enhancement
