Repository FabricMC/fabric-loader, pull requests merged in 2023-02, with the labels that each got.

#764 Improve the entrypoint patch reliability.
  minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java
  minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatch.java
Labels: bug

#763 Fix typo
  src/main/java/net/fabricmc/loader/api/FabricLoader.java
  src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java
Labels: merge me please

#767 Add fabric-loader-junit to allow unit testing of transformed classes.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  junit/.gitignore
  junit/build.gradle
  junit/src/main/java/net/fabricmc/loader/impl/junit/FabricLoaderLauncherSessionListener.java
  junit/src/main/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener
  minecraft/minecraft-test/build.gradle
  minecraft/minecraft-test/src/main/java/net/fabricmc/minecraft/test/mixin/MixinGrassBlock.java
  minecraft/minecraft-test/src/main/resources/fabricmc.test.mixins.client.json
  minecraft/minecraft-test/src/test/java/net/fabricmc/minecraft/test/junit/JunitTest.java
  minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java
  settings.gradle
  src/main/java/net/fabricmc/loader/impl/game/LoaderLibrary.java
  src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java
  src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java
  src/test/java/net/fabricmc/test/V1ModJsonParsingTests.java
Labels: enhancement

#774 Switch to ASCII characters for mod list tree formatting
  src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java
Labels: bug
