Repository FabricMC/fabric-loader, pull requests merged in 2023-10, with the labels that each got.

#841 Update to ASM 9.6
  gradle.properties
  src/main/resources/fabric-installer.json
  src/main/resources/fabric-installer.launchwrapper.json
Labels: merge me please

#837 Fix call to findResources returns empty.
  src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java
Labels: bug, merge me please

#831 Minor language changes for user readability
  src/main/java/net/fabricmc/loader/impl/discovery/ModResolver.java
  src/main/resources/net/fabricmc/loader/Messages.properties
Labels: merge me please

#802 Add an API method to more easily invoke entrypoints
  minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Hooks.java
  minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java
  src/main/java/net/fabricmc/loader/api/FabricLoader.java
  src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java
  src/main/java/net/fabricmc/loader/impl/entrypoint/EntrypointUtils.java
  src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java
Labels: enhancement, merge me please

#732 Unbreak EntrypointPatchFML125, again
  .gitignore
  minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatchFML125.java
Labels: bug, merge me please

#727 Add Spanish translation and make `StringUtil` capitalize the first letter, not character
  src/main/java/net/fabricmc/loader/impl/util/StringUtil.java
  src/main/resources/net/fabricmc/loader/Messages_es.properties
Labels: merge me please

#602 Use TLS
  src/main/resources/fabric.mod.json
Labels: enhancement

#801 Check for duplicate copies of loader on the classpath.
  src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java
  src/main/java/net/fabricmc/loader/impl/util/LoaderUtil.java
Labels: bug
